### ISSUE TITLE
Large amounts not correctly handled

### ISSUE THREAD

**Issue by alecalve** [shesek/bakshish#3]
If the amount is superior to 21M BTC (or possibly a smaller amount), an error should be returned.

```
LightningError: '999999999999999999999900000000000' is not a valid positive number                       
    at createError (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/error/typed.js:31:22)                                                                                               
    at LightningClient.once.res (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/lightning-client/index.js:109:28)                                                                      
    at Object.onceWrapper (events.js:272:13)        
    at LightningClient.emit (events.js:180:13)      
    at Parser.LightningClient.parser.onValue (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/lightning-client/index.js:59:17)                                                          
    at Parser.proto.emit (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:337:8)                                                                                 
    at Parser.proto.pop (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:332:8)                                                                                  
    at Parser.proto.onToken (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:402:12)                                                                             
    at Parser.proto.write (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/jsonparse/jsonparse.js:135:34)                                                                               
    at Socket.LightningClient.client.on.data (/home/[redacted]/.npm-packages/lib/node_modules/lightning-charge/node_modules/lightning-client/index.js:54:53)                                                          
    at Socket.emit (events.js:180:13)               
    at addChunk (_stream_readable.js:269:12)        
    at readableAddChunk (_stream_readable.js:256:11)                                                     
    at Socket.Readable.push (_stream_readable.js:213:10)                                                 
    at Pipe.onread (net.js:581:20) 
```

**Comment by shesek** [comment]
The maximum amount is really network dependent. Right now, both of Lightning Charge and nanotip are network agnostic and would run and whatever network the underlying c-lightning node is using (it currently supports bitcoin, litecoin and testnet), so I'm not sure they would be the right place to add this. I think it should be c-lightning's responsibility to reject impossible amounts? @cdecker
